server:
  port: 8081
#选择要激活那个环境块
spring:
  profiles:
    active: dev

---
server:
  port: 8083
spring:
  profiles: dev #配置环境的名称
person:
  email: 854377742@qq.com


---

server:
  port: 8084
spring:
  profiles: prod  #配置环境的名称
person:
  email: 111111111@qq.com
